"""fixes

Revision ID: 9046f66e9746
Revises: b0c9d6ace8f1
Create Date: 2026-05-23 13:11:52.098196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9046f66e9746'
down_revision: Union[str, Sequence[str], None] = 'b0c9d6ace8f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('matches', 'raw_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.add_column('player_matches', sa.Column('creep_score', sa.Integer(), nullable=False))
    op.add_column('player_matches', sa.Column('damage_dealt', sa.Integer(), nullable=False))
    op.alter_column('players', 'tag_line',
               existing_type=sa.VARCHAR(length=25),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('players', 'tag_line',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=25),
               existing_nullable=False)
    op.drop_column('player_matches', 'damage_dealt')
    op.drop_column('player_matches', 'creep_score')
    op.alter_column('matches', 'raw_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###
