"""fix_player_match_pks_and_queue_id

Revision ID: b0c9d6ace8f1
Revises: f2a670bd3f87
Create Date: 2026-05-22 18:36:31.008075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0c9d6ace8f1'
down_revision: Union[str, Sequence[str], None] = 'f2a670bd3f87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('queue_id', sa.Integer(), nullable=False))
    op.drop_column('matches', 'queue_iq')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('queue_iq', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('matches', 'queue_id')
    # ### end Alembic commands ###
