"""initial_migrations

Revision ID: f2a670bd3f87
Revises: 
Create Date: 2026-05-22 17:53:02.051045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2a670bd3f87'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('match_id', sa.String(length=30), nullable=False),
    sa.Column('match_created', sa.DateTime(timezone=True), nullable=False),
    sa.Column('match_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('queue_iq', sa.Integer(), nullable=False),
    sa.Column('patch', sa.String(length=16), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_table('players',
    sa.Column('puuid', sa.String(length=80), nullable=False),
    sa.Column('game_name', sa.String(length=50), nullable=False),
    sa.Column('tag_line', sa.String(length=25), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ranked_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('puuid')
    )
    op.create_index(op.f('ix_players_game_name'), 'players', ['game_name'], unique=False)
    op.create_index(op.f('ix_players_tag_line'), 'players', ['tag_line'], unique=False)
    op.create_table('player_matches',
    sa.Column('puuid', sa.String(length=80), nullable=False),
    sa.Column('match_id', sa.String(length=30), nullable=False),
    sa.Column('champion_id', sa.Integer(), nullable=False),
    sa.Column('champion_name', sa.String(length=50), nullable=False),
    sa.Column('kills', sa.Integer(), nullable=False),
    sa.Column('deaths', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('win', sa.Boolean(), nullable=False),
    sa.Column('team_position', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['puuid'], ['players.puuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('puuid', 'match_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_matches')
    op.drop_index(op.f('ix_players_tag_line'), table_name='players')
    op.drop_index(op.f('ix_players_game_name'), table_name='players')
    op.drop_table('players')
    op.drop_table('matches')
    # ### end Alembic commands ###
